//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Infusions/AbilityControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @AbilityControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @AbilityControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""AbilityControls"",
    ""maps"": [
        {
            ""name"": ""abilityMap"",
            ""id"": ""72717582-c482-4d12-a977-0fa383df89fe"",
            ""actions"": [
                {
                    ""name"": ""ability"",
                    ""type"": ""Button"",
                    ""id"": ""bae59a22-cb22-419a-a3e7-da591f1242e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold,Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""normal attack"",
                    ""type"": ""Button"",
                    ""id"": ""959a0a25-1512-4f2c-9f12-4a5658cf6585"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold,Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""819352d6-9267-4c35-acb8-52a677af39dd"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ability"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b87f6e8a-b040-4fb8-ad4c-9499ba1c09eb"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""normal attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // abilityMap
        m_abilityMap = asset.FindActionMap("abilityMap", throwIfNotFound: true);
        m_abilityMap_ability = m_abilityMap.FindAction("ability", throwIfNotFound: true);
        m_abilityMap_normalattack = m_abilityMap.FindAction("normal attack", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // abilityMap
    private readonly InputActionMap m_abilityMap;
    private IAbilityMapActions m_AbilityMapActionsCallbackInterface;
    private readonly InputAction m_abilityMap_ability;
    private readonly InputAction m_abilityMap_normalattack;
    public struct AbilityMapActions
    {
        private @AbilityControls m_Wrapper;
        public AbilityMapActions(@AbilityControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ability => m_Wrapper.m_abilityMap_ability;
        public InputAction @normalattack => m_Wrapper.m_abilityMap_normalattack;
        public InputActionMap Get() { return m_Wrapper.m_abilityMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AbilityMapActions set) { return set.Get(); }
        public void SetCallbacks(IAbilityMapActions instance)
        {
            if (m_Wrapper.m_AbilityMapActionsCallbackInterface != null)
            {
                @ability.started -= m_Wrapper.m_AbilityMapActionsCallbackInterface.OnAbility;
                @ability.performed -= m_Wrapper.m_AbilityMapActionsCallbackInterface.OnAbility;
                @ability.canceled -= m_Wrapper.m_AbilityMapActionsCallbackInterface.OnAbility;
                @normalattack.started -= m_Wrapper.m_AbilityMapActionsCallbackInterface.OnNormalattack;
                @normalattack.performed -= m_Wrapper.m_AbilityMapActionsCallbackInterface.OnNormalattack;
                @normalattack.canceled -= m_Wrapper.m_AbilityMapActionsCallbackInterface.OnNormalattack;
            }
            m_Wrapper.m_AbilityMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ability.started += instance.OnAbility;
                @ability.performed += instance.OnAbility;
                @ability.canceled += instance.OnAbility;
                @normalattack.started += instance.OnNormalattack;
                @normalattack.performed += instance.OnNormalattack;
                @normalattack.canceled += instance.OnNormalattack;
            }
        }
    }
    public AbilityMapActions @abilityMap => new AbilityMapActions(this);
    public interface IAbilityMapActions
    {
        void OnAbility(InputAction.CallbackContext context);
        void OnNormalattack(InputAction.CallbackContext context);
    }
}
